(WIP) Hashtable
chuigda/Project-CL pull request #12
Opened 2023-03-18 20:51 UTC by SchrodingerZhu

2023-03-19 03:55 UTC, chuigda requested changes

2023-03-19 03:55 UTC, chuigda commented on Makefile
> +	CFLAGS = -Wall -Wextra -pedantic -Werror -O2 -g $(EXTRA_CFLAGS)
Don't use `-Werror` anywhere under any circumstance.

2023-03-19 03:55 UTC, chuigda commented on src/cc_vec.c
> +    return cc_vec_remove_if2(vec, cc_vec_internal_remove_if_pred2, (void *)(&pred));
why we are taking the address of a pointer?

2023-03-19 03:55 UTC, chuigda commented on src/include/cc_impl.h
> +#define PROJECT_CL_IS_BIG_ENDIAN() (!*(unsigned char *)&(uint16_t){1})
We can make it part of `cc_cfg.h`, and make assertion in `cc_defs.c`.

2023-03-19 03:55 UTC, chuigda commented on include/cc_hash.h
> +typedef struct {
Why don't we make it more opaque?

2023-03-19 03:55 UTC, chuigda commented on include/cc_abort.h
> +CC_ATTRIBUTE_COLD _Bool cc_dump_stacktrace(void);
Would adding a `void` or not affect semantics of function declarations? I remembered that function declarations are actually more explicit than definitions...

2023-03-19 04:05 UTC, chuigda commented on Makefile
> +	CFLAGS = -Wall -Wextra -pedantic -Werror -O2 -g $(EXTRA_CFLAGS)
让我来解释一下这一点：随着时间发展，编译器肯定会不断改进，新的警告类别会被源源不断添加进去。考虑到我们作为*高素质*的 Project-CL 开发人员，肯定不会对这些警告熟视无睹，所以把它标记为错误与否并没有关系。与此相反，使用 Project-CL 的人可能会在某天升级编译器之后突然发现项目没法编译了。虽然 `CFLAGS` 可以从外部予以变更，但一个项目对 Project-CL 的依赖可能是嵌套在很深的地方的，比如 A -> B -> C -> D -> Project-CL，也就是开发者要改项目 D 指定的 Project-CL 编译配置，这在很多构建系统里都非常困难。而在这种情况下开发者甚至可能会 Fork 一份 D，这就引起了维护困难和事实上的社区分裂。所以由我们 —— 一个库的维护者 —— 来指定 `-Werror` 是绝对不行的。

2023-03-19 04:28 UTC, SchrodingerZhu commented on src/cc_vec.c
> +    return cc_vec_remove_if2(vec, cc_vec_internal_remove_if_pred2, (void *)(&pred));
casting function pointer to object pointer is incorrect in pedantic C

2023-03-19 04:29 UTC, SchrodingerZhu commented on include/cc_abort.h
> +CC_ATTRIBUTE_COLD _Bool cc_dump_stacktrace(void);
function declaration without void is not allowed in pedantic C.

2023-03-19 04:29 UTC, SchrodingerZhu commented on Makefile
> +	CFLAGS = -Wall -Wextra -pedantic -Werror -O2 -g $(EXTRA_CFLAGS)
agreed

2023-03-19 04:29 UTC, SchrodingerZhu commented
Also, please let me add some little tests before merging

2023-03-19 04:30 UTC, SchrodingerZhu commented on include/cc_hash.h
> +typedef struct {
do you mean a pointer? that would require allocs I suppose?

2023-03-19 05:16 UTC, SchrodingerZhu commented
@chuigda tests passed at https://github.com/SchrodingerZhu/cclib/pull/1

2023-03-20 02:20 UTC, SchrodingerZhu commented
hold on this. hash quality test failed. work on it.

2023-03-20 03:15 UTC, SchrodingerZhu commented
@chuigda seems fixed but let me make the whole report

2023-03-20 03:24 UTC, SchrodingerZhu commented
[cc-untable-hash-aarch64.txt](https://github.com/chuigda/Project-CL/files/11013397/cc-untable-hash-aarch64.txt)

2023-03-20 04:06 UTC, SchrodingerZhu commented
[cc-stable-hash-aarch64.txt](https://github.com/chuigda/Project-CL/files/11013612/cc-stable-hash-aarch64.txt)

2023-03-20 04:36 UTC, SchrodingerZhu commented
I think it is ready for merge now. I am not sure about the formatting you required. Do you have time to format and reorder the macros as you wish?

2023-03-21 01:29 UTC, chuigda approved these changes

2023-03-21 01:29 UTC, merged